site_name: Daisy DB Documentation
docs_dir: "daisy db documentation/docs"
site_description: >-
  AimeDB | INFO | daisy
site_author: ヾ(゜Д゜)ノ

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/weather-night
        name: yeah, my eyes also hurt
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: are you switching to light mode? weirdo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Welcome Back: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Transcriptions: getting-started/transcriptions.md
  - Database Workflow:
      - Creating the Database: workflow/starting.md
      - Segmentation & Annotation: workflow/segmentation.md
      - Dictionary & Custom G2PA: workflow/dictionary-g2pa.md
  - Compiling & Packaging:
      - Compiling the Database: compiling/compiling.md
      - Component IDs & .vvd: compiling/component-ids.md
      - Editor Import: compiling/editor-import.md
  - FAQ: faq.md
  - Resources: resources.md
